version: '3.7'
services:
  mqtt:
    image: eclipse-mosquitto:1.6.9
    restart: always
    ports:
      - "1883:1883"
  
  influxdb:
    image: influxdb:1.8.0
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb/data:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=home_measurements
      - INFLUXDB_USER=home
      - INFLUXDB_USER_PASSWORD=secret-password
      - INFLUXDB_REPORTING_DISABLED=true

  mqtt-forwarder:
    build: ./mqtt-forwarder
    restart: always
    environment:
      - INFLUXDB_DB=home_measurements
      - INFLUXDB_USER=home
      - INFLUXDB_USER_PASSWORD=secret-password
    depends_on:
      - mqtt
      - influxdb
  
  grafana:
    image: grafana/grafana:6.7.2
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
