/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_PB_DATA_PB_H_INCLUDED
#define PB_PB_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _pb_WeatherData {
    int32_t deviceId;
    float temperature;
    float humidity;
    float pressure;
    float IAQ;
    int32_t iaq_accuracy;
} pb_WeatherData;


/* Initializer values for message structs */
#define pb_WeatherData_init_default              {0, 0, 0, 0, 0, 0}
#define pb_WeatherData_init_zero                 {0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pb_WeatherData_deviceId_tag              1
#define pb_WeatherData_temperature_tag           2
#define pb_WeatherData_humidity_tag              3
#define pb_WeatherData_pressure_tag              4
#define pb_WeatherData_IAQ_tag                   5
#define pb_WeatherData_iaq_accuracy_tag          6

/* Struct field encoding specification for nanopb */
#define pb_WeatherData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    deviceId,          1) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature,       2) \
X(a, STATIC,   REQUIRED, FLOAT,    humidity,          3) \
X(a, STATIC,   REQUIRED, FLOAT,    pressure,          4) \
X(a, STATIC,   REQUIRED, FLOAT,    IAQ,               5) \
X(a, STATIC,   REQUIRED, INT32,    iaq_accuracy,      6)
#define pb_WeatherData_CALLBACK NULL
#define pb_WeatherData_DEFAULT NULL

extern const pb_msgdesc_t pb_WeatherData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pb_WeatherData_fields &pb_WeatherData_msg

/* Maximum encoded size of messages (where known) */
#define pb_WeatherData_size                      42

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
