/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_SRC_DATA_PB_H_INCLUDED
#define PB_SRC_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _WeatherData {
    int32_t deviceId;
    float temperature;
    float humidity;
    float pressure;
    float IAQ;
    int32_t iaq_accuracy;
    float CO2;
    float breath_VOC;
} WeatherData;


/* Initializer values for message structs */
#define WeatherData_init_default                 {0, 0, 0, 0, 0, 0, 0, 0}
#define WeatherData_init_zero                    {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define WeatherData_deviceId_tag                 1
#define WeatherData_temperature_tag              2
#define WeatherData_humidity_tag                 3
#define WeatherData_pressure_tag                 4
#define WeatherData_IAQ_tag                      5
#define WeatherData_iaq_accuracy_tag             6
#define WeatherData_CO2_tag                      7
#define WeatherData_breath_VOC_tag               8

/* Struct field encoding specification for nanopb */
#define WeatherData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    deviceId,          1) \
X(a, STATIC,   REQUIRED, FLOAT,    temperature,       2) \
X(a, STATIC,   REQUIRED, FLOAT,    humidity,          3) \
X(a, STATIC,   REQUIRED, FLOAT,    pressure,          4) \
X(a, STATIC,   REQUIRED, FLOAT,    IAQ,               5) \
X(a, STATIC,   REQUIRED, INT32,    iaq_accuracy,      6) \
X(a, STATIC,   REQUIRED, FLOAT,    CO2,               7) \
X(a, STATIC,   REQUIRED, FLOAT,    breath_VOC,        8)
#define WeatherData_CALLBACK NULL
#define WeatherData_DEFAULT NULL

extern const pb_msgdesc_t WeatherData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WeatherData_fields &WeatherData_msg

/* Maximum encoded size of messages (where known) */
#define WeatherData_size                         52

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
