apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
- name: InfluxDB
  type: influxdb
  typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
  access: proxy
  url: http://influxdb:8086
  password: secret-password
  user: home
  database: home_measurements
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
    keepCookies: []
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true